#!/usr/bin/env tsx
/**
 * 021/Track 7 — Translate an EN benchmark corpus into UA or PL via DeepL.
 *
 * Reads the source JSONL from `packages/cli/corpora/<source>.jsonl`, splits
 * each line into the corpus-types shape, hands every text-bearing field to
 * `translateCorpus` (deep module), and writes the result to
 * `packages/cli/corpora/<source-prefix>-<target>.jsonl`.
 *
 * Usage:
 *   DEEPL_API_KEY=... pnpm tsx packages/cli/scripts/translate-corpus.ts \
 *     --source valis-multilingual-en --target uk
 *
 * Provenance is recorded automatically via `metadata.translation`
 * (source_id, target_lang, provider, content_hash). After running, refresh
 * `LICENSE-CORPUS.md` with the new file's SHA-256 + fetched_at date.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  translateCorpus,
  type CorpusLineRecord,
  type TargetLanguage,
  type TranslationApi,
} from '../src/benchmarks/corpus-translator.js';

interface CliArgs {
  source: string;
  target: TargetLanguage;
}

function parseArgs(): CliArgs {
  const args = process.argv.slice(2);
  let source = '';
  let target = '';
  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--source') source = args[++i] ?? '';
    else if (args[i] === '--target') target = args[++i] ?? '';
  }
  if (!source || !target) {
    console.error(
      'usage: translate-corpus --source <corpus-id> --target <uk|pl|de|ja>',
    );
    process.exit(2);
  }
  if (target !== 'uk' && target !== 'pl' && target !== 'de' && target !== 'ja') {
    console.error(`invalid --target: ${target} (must be uk, pl, de, or ja)`);
    process.exit(2);
  }
  return { source, target };
}

/**
 * Thin adapter over DeepL's REST API (free tier). Sends each chunk as a
 * separate `text` field — DeepL preserves order in the response array.
 *
 * `fetchImpl` and `endpoint` are seam params so unit tests can run without
 * hitting the real DeepL service.
 */
export function createDeepLApi(
  apiKey: string,
  fetchImpl: typeof fetch = fetch,
  endpoint: string = 'https://api-free.deepl.com/v2/translate',
): TranslationApi {
  return {
    async translate(chunks, target) {
      const params = new URLSearchParams();
      for (const c of chunks) params.append('text', c);
      params.append('source_lang', 'EN');
      params.append('target_lang', target.toUpperCase());

      const res = await fetchImpl(endpoint, {
        method: 'POST',
        headers: {
          Authorization: `DeepL-Auth-Key ${apiKey}`,
          'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: params.toString(),
      });
      if (!res.ok) {
        const err = new Error(
          `DeepL ${res.status}: ${(await res.text()).slice(0, 200)}`,
        ) as Error & { status?: number };
        err.status = res.status;
        throw err;
      }
      const body = (await res.json()) as { translations: Array<{ text: string }> };
      return body.translations.map((t) => t.text);
    },
  };
}

/**
 * Parse a JSONL corpus body, skipping comment lines (`#`-prefix) and blank
 * lines. Exported for unit testing — main() inlines this same loop.
 */
export function parseCorpusBody(raw: string): CorpusLineRecord[] {
  const seed: CorpusLineRecord[] = [];
  for (const line of raw.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    seed.push(JSON.parse(trimmed) as CorpusLineRecord);
  }
  return seed;
}

async function main(): Promise<void> {
  const apiKey = process.env.DEEPL_API_KEY;
  if (!apiKey) {
    console.error('DEEPL_API_KEY required — get one at https://www.deepl.com/pro-api');
    process.exit(2);
  }

  const { source, target } = parseArgs();

  // Resolve corpora dir from this script's location: scripts/ → ../corpora.
  const here = dirname(fileURLToPath(import.meta.url));
  const corporaDir = resolve(here, '../corpora');
  const sourcePath = resolve(corporaDir, `${source}.jsonl`);

  // Build target slice ID by replacing the trailing language tag, e.g.
  // valis-multilingual-en → valis-multilingual-uk.
  const targetId = source.endsWith('-en')
    ? `${source.slice(0, -3)}-${target}`
    : `${source}-${target}`;
  const targetPath = resolve(corporaDir, `${targetId}.jsonl`);

  const raw = await readFile(sourcePath, 'utf-8');
  const seed = parseCorpusBody(raw);

  console.log(`Translating ${seed.length} lines from ${source} → ${target}…`);
  const api = createDeepLApi(apiKey);
  const translated = await translateCorpus(seed, target, api);

  // Emit a leading comment so future readers know how to regenerate.
  const header = [
    `# ${targetId} — generated by packages/cli/scripts/translate-corpus.ts`,
    `# source: ${source}.jsonl`,
    `# provider: DeepL Free API`,
    `# regenerate: DEEPL_API_KEY=... pnpm tsx packages/cli/scripts/translate-corpus.ts --source ${source} --target ${target}`,
  ].join('\n');
  const body = translated.map((line) => JSON.stringify(line)).join('\n');
  await writeFile(targetPath, `${header}\n${body}\n`, 'utf-8');

  console.log(`Wrote ${targetPath} (${translated.length} lines).`);
  console.log('Next: update LICENSE-CORPUS.md with the new file SHA-256 + fetched_at.');
}

// Direct-invocation guard so importing this module (for tests) does not
// trigger main(). Matches the resolved file-path against process.argv[1].
const invokedDirectly =
  process.argv[1] !== undefined &&
  import.meta.url === `file://${process.argv[1]}`;

if (invokedDirectly) {
  main().catch((err) => {
    console.error('translate-corpus: fatal error', err);
    process.exit(1);
  });
}
